name: CloudSim Auto-Scaling CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Create libs directory
      run: mkdir -p libs

    - name: Download required JARs
      run: |
        wget https://repo1.maven.org/maven2/org/apache/commons/commons-math4-legacy/4.0-beta1/commons-math4-legacy-4.0-beta1.jar -O libs/commons-math4-legacy-4.0-beta1.jar
        wget https://github.com/Cloudslab/cloudsim/releases/download/v3.0.3/cloudsim-3.0.3.jar -O libs/cloudsim-3.0.3.jar || echo "CloudSim JAR not found – fallback manually or build from source"

    - name: Install CloudSim JAR into local Maven repository
      run: |
        # Download and install CloudSim JAR directly to local Maven repo
        wget -q https://github.com/Cloudslab/cloudsim/releases/download/v3.0.3/cloudsim-3.0.3.jar -O cloudsim-3.0.3.jar
        mvn install:install-file -Dfile=cloudsim-3.0.3.jar -DgroupId=org.cloudbus.cloudsim -DartifactId=cloudsim -Dversion=3.0.3 -Dpackaging=jar
        
        # If download fails, build from source
        if [ $? -ne 0 ]; then
          echo "Failed to download CloudSim JAR, building from source..."
          wget https://github.com/Cloudslab/cloudsim/archive/refs/tags/cloudsim-3.0.3.zip
          unzip cloudsim-3.0.3.zip
          cd cloudsim-cloudsim-3.0.3/modules/cloudsim
          mvn clean install -DskipTests -Dmaven.javadoc.skip=true
        fi

    - name: Build with Maven
      run: mvn -B package

    - name: Run Auto-Scaling Tests
      run: mvn test -Dtest=AutoScalingTests

    - name: Generate JaCoCo test coverage report
      run: mvn jacoco:report

    - name: Archive test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/site/jacoco/