name: CloudSim Auto-Scaling CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Create libs directory
      run: mkdir -p libs

    - name: Download CloudSim 3.0.3
      run: |
        wget https://github.com/Cloudslab/cloudsim/releases/download/cloudsim-3.0.3/cloudsim-3.0.3.jar -O libs/cloudsim-3.0.3.jar
        wget https://repo1.maven.org/maven2/org/apache/commons/commons-math4-legacy/4.0-beta1/commons-math4-legacy-4.0-beta1.jar -O libs/commons-math4-legacy-4.0-beta1.jar

    - name: Build with Maven
      run: mvn -B package

    - name: Run Auto-Scaling Tests
      run: mvn test -Dtest=AutoScalingTests

    - name: Generate JaCoCo test coverage report
      run: mvn jacoco:report

    - name: Archive test reports
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/site/jacoco/